name: CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

  controller:
    name: configmap controller build
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      DOCKER_IMAGE_URL: ghcr.io/mxcd/configmap-controller
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build
        run: docker build --platform=linux/amd64 -t configmap-controller .

      - name: Docker push
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        run: |
          export URL=${DOCKER_IMAGE_URL}:${{ github.ref_name }}
          docker tag configmap-controller $URL
          docker push $URL
